### PR TITLE
Add POST support for /series

### PR DESCRIPTION
**Pull request by oronsh**
Addresses this issue: https://github.com/prometheus-community/prom-label-proxy/issues/90

### CODE REVIEW

**Review by squat — COMMENTED** [review]
Thank you! Would you consider adding a unit test for this case?

**Comment by oronsh** [comment]
Yes of course!

**Review by squat — APPROVED** [review]
thanks @oronsh
that was very thorough and fast!

**Comment by oronsh** [comment]
> thanks @oronsh that was very thorough and fast!

Thank you for fast handling this PR, this was important for my company!

**Pull request merged**
