### PR TITLE
chore: cut v0.9.0

### PR DESCRIPTION
**Pull request by simonpasquier**

### CODE REVIEW

**Review by SuperQ — COMMENTED** [review]
Would you mind updating promu and CI to Go 1.22?

**Comment by SuperQ** [comment]
Weird that DCO is stalled

**Review by squat — APPROVED** [review]
lgtmmmmm

**Comment by simonpasquier** [comment]
The DCO issue is global: https://github.com/dcoapp/app/issues/211

**Comment by squat** [comment]
overriding and merging

**Comment by SuperQ** [comment]
Nice

**Pull request merged**
